In [1]:
import pandas as pd

In [2]:
irl = pd.read_csv('more-than1-neigh.csv', index_col = 'Unnamed: 0')

In [3]:
irl

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
0,"5 Braemor Drive, Churchtown",NaN,Dublin,343000.0,1,1,1,0,2010,1,Churchtown Dublin,Dublin,0,Braemor Drive Churchtown Dublin,Leinster,Estate
1,"134 Ashewood Walk, Summerhill Lane, Portlaoise",NaN,Laois,185000.0,1,0,0,1,2010,1,Portlaoise,Midlands,0,Summerhill Lane Portlaoise,Leinster,Estate
2,"1 The Haven, Mornington",NaN,Meath,400000.0,1,1,1,1,2010,1,Mornington,Mid-East,0,The Haven Mornington,Leinster,Estate
3,"12 Sallymount Avenue, Ranelagh",NaN,Dublin,425000.0,1,1,1,1,2010,1,Ranelagh,Dublin,0,Sallymount Avenue Ranelagh,Leinster,Estate
4,"15 Carriglawn, Waterpark, Carrigaline",NaN,Cork,180000.0,1,1,1,1,2010,1,Carrigaline,South-West (IE),0,Waterpark Carrigaline,Munster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255730,"5 Grange Park Rd, Waterford, Waterford",NaN,Waterford,515000.0,1,1,1,2,2021,2,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255731,"173 Hennessys Rd, Waterford, Waterford",NaN,Waterford,125000.0,1,1,1,2,2021,3,Waterford,South East (IE),0,Hennessys Road Waterford,Munster,Estate
255732,"15 Grange Park Rd, Waterford, Waterford",NaN,Waterford,390000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255733,"40 Ballytruckle Rd, Waterford, Waterford",NaN,Waterford,115000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Ballytruckle Road Waterford,Munster,Estate
255734,"11 St Alphonsus Rd, Waterford, Waterford",NaN,Waterford,178000.0,1,1,1,2,2021,7,Waterford,South East (IE),0,St. Alphonsus Road Waterford,Munster,Estate

## Updating Towns and Neighbourhoods
In my earlier data cleaning I took a list of towns and villages in each county and tried to find them within addresses. If they were not found in any way they would be denoted as "X county" and later removed. This was due to the fact these were either incorrectly spelt or just a rural townland with no real predictive power. However, in some of my counties, let's take Cork as an example, I had "Cork" and "Cork City" in my town list. That's because a lot of the addresses would denote the city as simply Cork. However, some of these may contain incorrect spellings of a town or a rural townland containing Cork at the end of the address. Let's say the address was denoted as ***Youghl, Cork***. The way the function was set up was that if it found nothing on the 2nd to last string it would take the last string if it was in our list of towns. As a result some of our values may be faulty with such towns/cities, which typically possess the same name as the county they are from. This would affect the predictive power of our model without doubt. With our column of neighbourhoods now added we can root out these faulty values a bit easier and detect any spelling errors too. This will involve a degree of manual searching online for some townlands/areas but I feel it is a worthwhile experiment to improve our model further.

### Cork

In [4]:
crk = irl.loc[irl['Town'] == 'Cork']

In [5]:
irl.drop(irl[irl['Town'] == "Cork"].index, inplace=True)

In [6]:
irl.loc[irl['Town'] == 'Cork City']

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
1310,"27 Doyle Road, Turners Cross",NaN,Cork,225000.0,1,1,1,1,2010,2,Cork City,South-West (IE),0,Turners Cross Cork City,Munster,Estate
1878,"15 Capwell Road, Turners Cross",NaN,Cork,160000.0,0,1,1,1,2010,3,Cork City,South-West (IE),0,Turners Cross Cork City,Munster,Estate
2519,"14 St Josephs, Derrynane Road, Turners Cross",NaN,Cork,193000.0,1,1,1,1,2010,4,Cork City,South-West (IE),0,Turners Cross Cork City,Munster,Estate
3206,"10 St Annes Park, Derrynane Road, Turners Cross",NaN,Cork,193000.0,1,1,1,0,2010,5,Cork City,South-West (IE),0,Turners Cross Cork City,Munster,Estate
3565,"59 Father Matthew Road, Turners Cross",NaN,Cork,163000.0,1,1,1,1,2010,5,Cork City,South-West (IE),0,Turners Cross Cork City,Munster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251478,"28 Aylesbury, Ballintemple, Cork City",NaN,Cork,436123.0,1,0,0,1,2020,6,Cork City,South-West (IE),0,Ballintemple Cork City,Munster,Estate
251672,"37 The Rise, Bishopstown, Cork City",NaN,Cork,399000.0,1,1,1,1,2020,8,Cork City,South-West (IE),0,Bishopstown Cork City,Munster,Estate
252112,"26 Palmbury Orchard, Togher, Cork City",NaN,Cork,210000.0,1,1,1,2,2020,12,Cork City,South-West (IE),0,Togher Cork City,Munster,Estate
252310,"44 Hillside Rd, Glasheen, Cork City",NaN,Cork,335000.0,1,1,1,2,2021,2,Cork City,South-West (IE),0,Glasheen Cork City,Munster,Estate
252619,"31 Sandymount Ave, Glasheen, Cork City",NaN,Cork,285000.0,1,1,1,2,2021,5,Cork City,South-West (IE),0,Glasheen Cork City,Munster,Estate

In [7]:
m = pd.DataFrame(crk['Neighbourhood'].unique())
#m.to_csv('cork-unqiue.csv')

In [8]:
# Upr Fair Hill Cork
# Ballyphenane Cork
# Patricks Hill Cork - St....
# Farrenree Cork - a instead first e

In [9]:
rm_crk =  ['Glenville Cork' , 'Clonakility Cork', 'Bere Island Cork', 'Ballinure Cork', 'Carrignavar Cork', 'Garryvoe Cork',
'Lissarda Cork', 'Balllincollig Cork', 'Carrigtohill Cork', 'Maryborough Woods Douglas Cork', 'Riverstown Glanmire Cork',
'Carrigohane Cork', 'Kildinan Cork', 'Gurranbraher Cork', 'Berrings Cork', 'Curaheen Cork', 'Riverstown Cork', 
'Maryborough Hill Douglas Cork', 'Leamlara Cork', 'Douglas Village Cork', 'Donnybrook Douglas Cork',
'Grange Douglas Cork', 'Ballydaly Cork', 'Douglas Cork Cork', 'Kilcully Cork', 'Inniscarra Cork', 'Dromahane Mallow Cork',
'Glengarrif Cork', 'Off Dominick Street Cork', 'Garrettstown Cork', 'Ballynoe Cork', 'Classes Lake Ovens Cork', 'Glounthane Cork',
'Glanmire Village Cork', 'Ardcashel Watergrasshill Cork', 'Owenahincha Cork', 'Michelstown Cork', 'Sallybrook Glanmire Cork',
'Myrtleville Cork', 'Bishopstown Cork Cork', 'Mogeely Cork', 'Rathpeacon Cork', 'Upper Rochestown Cork', 'Currabinny Cork',
'Millstreet Town Cork', 'Courtbrack Cork', 'Mount Oval Village Rochestown Cork', 'Dromina Cork', 'Street Cork',
'Inchigeelagh Cork', 'Inchigeela Cork', 'Gillabbey Cork', 'Shanavoher Beewng Cork', 'Roscarbery Cork', 'Beara Cork',
'Glouthaune Cork', 'Ballyfeard Cork', 'Raffeen Hill Monkstown Cork', 'Carrig Na Bhfear Cork', 'Burnfort Mallow Cork',
'Castlefreke Cork', 'Seafield Youghal Cork', 'Thornbury View Rochestown Cork', 'Janeville Cork', 'Burnfort Cork',
'The Pines Rushbrooke Links Cobh Cork', 'Barrymore Ave Cobh Cork', 'Kilmoney Cork', 'Bartlemy Cork', 'Curraheen Road Bishopstown Cork',
'Maglin Road Ballincollig Cork', 'Sarsfield Road Wilton Cork', 'Granagh Cork', 'Rathcoole Cork']

In [10]:
crk.shape

(6645, 16)

In [11]:
crk.drop(crk[crk['Neighbourhood'].isin(rm_crk)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [12]:
crk.shape

(6310, 16)

In [13]:
crk.loc[crk['Neighbourhood'].str.contains("Fair Hill"), 'Neighbourhood'] = "Fair Hill Cork"
crk.loc[crk['Neighbourhood'].str.contains("Ballyphenane Cork"), 'Neighbourhood'] = "Ballyphehane Cork"
crk.loc[crk['Neighbourhood'].str.contains("Patricks Hill Cork"), 'Neighbourhood'] = "St. Patricks Hill Cork"
crk.loc[crk['Neighbourhood'].str.contains("Farrenree Cork"), 'Neighbourhood'] = 'Farranree Cork'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [14]:
crk['Town'] = 'Cork City'

C:\Users\user\AppData\Local\Temp/ipykernel_17744/3774906381.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crk['Town'] = 'Cork City'

In [15]:
crk

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
140143,"78 Sundays Well Road, Cork",NaN,Cork,510000.0,1,1,1,2,2010,1,Cork City,South-West (IE),0,Sundays Well Road Cork,Munster,Estate
140144,"11 Glasheen Park, Magazine Road, Cork",NaN,Cork,265000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Magazine Road Cork,Munster,Estate
140145,"547 The Heron, Jacobs Island, Cork",NaN,Cork,200000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Jacobs Island Cork,Munster,Estate
140146,"79 Cardinal Court, Wilton, Cork",NaN,Cork,245000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Wilton Cork,Munster,Estate
140147,"3 Newenham Terrace, Infirmary Road, Cork",NaN,Cork,410000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Infirmary Road Cork,Munster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255575,"1 Alderwood, Douglas Rd South, Cork",NaN,Cork,275000.0,1,1,1,1,2020,10,Cork City,South-West (IE),0,Douglas Road South Cork,Munster,Estate
255576,"115 Greenhills Court, Douglas Rd South, Cork",NaN,Cork,246000.0,1,1,1,1,2020,10,Cork City,South-West (IE),0,Douglas Road South Cork,Munster,Estate
255577,"6 Hillgrove Lawn, Douglas Rd South, Cork",NaN,Cork,479000.0,1,1,1,2,2020,11,Cork City,South-West (IE),0,Douglas Road South Cork,Munster,Estate
255578,"90 Greenhills Court, Douglas Rd South, Cork",NaN,Cork,200000.0,1,1,1,2,2020,11,Cork City,South-West (IE),0,Douglas Road South Cork,Munster,Estate
255579,"7 Palaceanne Court, Douglas Rd South, Cork",NaN,Cork,310000.0,1,1,1,2,2021,8,Cork City,South-West (IE),0,Douglas Road South Cork,Munster,Estate

In [16]:
irl = pd.concat([crk, irl], ignore_index = True)

In [17]:
irl

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
0,"78 Sundays Well Road, Cork",NaN,Cork,510000.0,1,1,1,2,2010,1,Cork City,South-West (IE),0,Sundays Well Road Cork,Munster,Estate
1,"11 Glasheen Park, Magazine Road, Cork",NaN,Cork,265000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Magazine Road Cork,Munster,Estate
2,"547 The Heron, Jacobs Island, Cork",NaN,Cork,200000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Jacobs Island Cork,Munster,Estate
3,"79 Cardinal Court, Wilton, Cork",NaN,Cork,245000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Wilton Cork,Munster,Estate
4,"3 Newenham Terrace, Infirmary Road, Cork",NaN,Cork,410000.0,1,1,1,1,2010,1,Cork City,South-West (IE),0,Infirmary Road Cork,Munster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255395,"5 Grange Park Rd, Waterford, Waterford",NaN,Waterford,515000.0,1,1,1,2,2021,2,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255396,"173 Hennessys Rd, Waterford, Waterford",NaN,Waterford,125000.0,1,1,1,2,2021,3,Waterford,South East (IE),0,Hennessys Road Waterford,Munster,Estate
255397,"15 Grange Park Rd, Waterford, Waterford",NaN,Waterford,390000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255398,"40 Ballytruckle Rd, Waterford, Waterford",NaN,Waterford,115000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Ballytruckle Road Waterford,Munster,Estate
255399,"11 St Alphonsus Rd, Waterford, Waterford",NaN,Waterford,178000.0,1,1,1,2,2021,7,Waterford,South East (IE),0,St. Alphonsus Road Waterford,Munster,Estate

In [18]:
lim = irl.loc[irl['Town'] == 'Limerick']

In [19]:
#lim

In [20]:
lim_city = irl.loc[irl['Town'] == 'Limerick City']

In [21]:
#lim_city

In [22]:
wat = irl.loc[irl['Town'] == 'Waterford']

In [23]:
#wat

In [24]:
lon = irl.loc[irl['Town'] == 'Longford']

In [25]:
#lon

In [26]:
ros = irl.loc[irl['Town'] == 'Roscommon']

In [27]:
#ros

In [28]:
cav = irl.loc[irl['Town'] == 'Cavan']

In [29]:
#cav

In [30]:
mon = irl.loc[irl['Town'] == 'Monaghan']

In [31]:
#mon

In [32]:
don = irl.loc[irl['Town'] == 'Donegal']

In [33]:
#don

### Roscommon

In [34]:
ros

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
164348,"Ballypheason, Galway Road, Roscommon",NaN,Roscommon,246696.03,1,0,0,2,2010,1,Roscommon,West,0,Galway Road Roscommon,Connacht,Other
164349,"10 Woodberry Court, Golf Links Road, Roscommon",NaN,Roscommon,140969.15,1,0,0,2,2010,1,Roscommon,West,0,Golf Links Road Roscommon,Connacht,Estate
164350,"14 Woodberry Court, Golf Links Road, Roscommon",NaN,Roscommon,140969.15,1,0,0,2,2010,1,Roscommon,West,0,Golf Links Road Roscommon,Connacht,Estate
164351,"Convent Road, Roscommon",NaN,Roscommon,121000.00,1,1,1,2,2010,1,Roscommon,West,0,Convent Road Roscommon,Connacht,Other
164352,"6 Essex Grove, Roscommon",NaN,Roscommon,130000.00,1,1,1,2,2010,2,Roscommon,West,0,Essex Grove Roscommon,Connacht,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253401,"Tully, Ballygar, Roscommon",NaN,Roscommon,140000.00,1,1,1,1,2020,8,Roscommon,West,0,Ballygar Roscommon,Connacht,Other
253403,"Cloonbrackna Court, Roscommon, Roscommon",NaN,Roscommon,192000.00,1,1,1,1,2020,9,Roscommon,West,0,Cloonbrackna Court Roscommon,Connacht,Other
253404,"Abbey St, Roscommon, Roscommon",NaN,Roscommon,115000.00,1,1,1,2,2020,10,Roscommon,West,0,Abbey Street Roscommon,Connacht,Other
253405,"Ardcarn Shannonbridge Rd, Ballinasloe, Roscommon",NaN,Roscommon,162000.00,1,1,1,2,2021,3,Roscommon,West,0,Ballinasloe Roscommon,Connacht,Other
253472,"Mount Talbot, Roscommon, Co Roscommon",NaN,Roscommon,100000.00,1,1,1,1,2014,5,Roscommon,West,0,Mount Talbot Roscommon,Connacht,Other

In [35]:
ross = pd.DataFrame(ros['Neighbourhood'].unique())

In [36]:
#ross.to_csv('ros-neighss.csv')

In [37]:
### fix
# Ardsallagh Beg Roscommon - Ardsallaghbeg Roscommon /done
# Ardsallagh More Roscommon - Ardsallaghmore Roscommon
# Ard Sallaghbeg Roscommon - Ardsallaghbeg Roscommon
# Clooneybeirne Roscommon - Cloonybeirne Roscommon

In [38]:
rm_ros = ['Donamon Roscommon', 'French Park Roscommon', 'Woodside Park Ballaghaderreen Roscommon', 'Balaghaderreen Roscommon',
         'Cootehall Roscommon', 'Ballinaheglish Roscommon', 'Ballaghadreen Roscommon', 'Ballinagare Roscommon', 'Loughlynn Roscommon',
         'Ballaghderreen Roscommon', 'Brideswell Athlone Roscommon', 'Baylough Athlone Roscommon', 'Taughmaconnell Roscommon',
         'Ballintubber Roscommon', 'Ballinasloe Roscommon', 'Lanesborough Roscommon', 'Ballygar Roscommon', 'Mount Talbot Roscommon',
         'Corrigeenroe Roscommon', 'Ballinameen Roscommon', 'Scramogue Roscommon', 'Kiltoom Roscommon', 'Rooskey Roscommon',
         'Monksland Athlone Roscommon', 'Greenhills Ballinameen Boyle Roscommon', 'Mullymucks Roscommon', 'Curraghroe Roscommon',
         'Fourmile House Roscommon', 'Mote Park Roscommon', 'Castlecoote Roscommon', 'Mullymucks Roscommon',
         'Ballinaheglish Roscommon', 'Ballymacurley Roscommon', 'Ashbrook Roscommon', 'Cloverhill Roscommon',
         'Ballymacurley Roscommon', 'Bealnamulla Athlone Roscommon', 'Roxborough Roscommon']

In [39]:
irl.drop(irl[irl['Town'] == "Roscommon"].index, inplace=True)

In [40]:
ros.shape

(786, 16)

In [41]:
ros.drop(ros[ros['Neighbourhood'].isin(rm_ros)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [42]:
ros.shape

(600, 16)

In [43]:
ros.loc[ros['Neighbourhood'].str.contains("Ardsallagh Beg"), 'Neighbourhood'] = 'Ardsallaghbeg Roscommon'
ros.loc[ros['Neighbourhood'].str.contains("Ard Sallaghbeg"), 'Neighbourhood'] = 'Ardsallaghbeg Roscommon'
ros.loc[ros['Neighbourhood'].str.contains("Ardsallagh More Roscommon"), 'Neighbourhood'] = "Ardsallaghmore Roscommon"
ros.loc[ros['Neighbourhood'].str.contains("Clooneybeirne Roscommon"), 'Neighbourhood'] = 'Cloonybeirne Roscommon'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [44]:
ros['Town'] = 'Roscommon Town'

C:\Users\user\AppData\Local\Temp/ipykernel_17744/1656569284.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ros['Town'] = 'Roscommon Town'

In [45]:
irl = pd.concat([ros, irl], ignore_index = True)

In [46]:
irl

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
0,"Ballypheason, Galway Road, Roscommon",NaN,Roscommon,246696.03,1,0,0,2,2010,1,Roscommon Town,West,0,Galway Road Roscommon,Connacht,Other
1,"10 Woodberry Court, Golf Links Road, Roscommon",NaN,Roscommon,140969.15,1,0,0,2,2010,1,Roscommon Town,West,0,Golf Links Road Roscommon,Connacht,Estate
2,"14 Woodberry Court, Golf Links Road, Roscommon",NaN,Roscommon,140969.15,1,0,0,2,2010,1,Roscommon Town,West,0,Golf Links Road Roscommon,Connacht,Estate
3,"Convent Road, Roscommon",NaN,Roscommon,121000.00,1,1,1,2,2010,1,Roscommon Town,West,0,Convent Road Roscommon,Connacht,Other
4,"6 Essex Grove, Roscommon",NaN,Roscommon,130000.00,1,1,1,2,2010,2,Roscommon Town,West,0,Essex Grove Roscommon,Connacht,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255209,"5 Grange Park Rd, Waterford, Waterford",NaN,Waterford,515000.00,1,1,1,2,2021,2,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255210,"173 Hennessys Rd, Waterford, Waterford",NaN,Waterford,125000.00,1,1,1,2,2021,3,Waterford,South East (IE),0,Hennessys Road Waterford,Munster,Estate
255211,"15 Grange Park Rd, Waterford, Waterford",NaN,Waterford,390000.00,1,1,1,2,2021,5,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255212,"40 Ballytruckle Rd, Waterford, Waterford",NaN,Waterford,115000.00,1,1,1,2,2021,5,Waterford,South East (IE),0,Ballytruckle Road Waterford,Munster,Estate
255213,"11 St Alphonsus Rd, Waterford, Waterford",NaN,Waterford,178000.00,1,1,1,2,2021,7,Waterford,South East (IE),0,St. Alphonsus Road Waterford,Munster,Estate

### Longford

In [47]:
lon

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
175850,"42 Oakvale, Longford, Co Longford",NaN,Longford,31000.0,1,1,1,1,2013,12,Longford,Midlands,0,Oakvale Longford,Leinster,Estate
175871,"Glack, Longford, Co Longford",NaN,Longford,115000.0,1,1,1,1,2014,10,Longford,Midlands,0,Glack Longford,Leinster,Other
175872,"Ferefad, Longford, Co Longford",NaN,Longford,51000.0,1,1,1,1,2014,11,Longford,Midlands,0,Ferefad Longford,Leinster,Other
175880,"No 17 Battery Court, Longford, Co Longford",NaN,Longford,65000.0,1,1,1,2,2015,1,Longford,Midlands,0,Battery Court Longford,Leinster,Other
175886,"Dublin Road, Longford, Co Longford",NaN,Longford,68000.0,1,1,1,1,2015,3,Longford,Midlands,0,Dublin Road Longford,Leinster,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253646,"Deanscurragh, Longford, Longford",NaN,Longford,142500.0,1,1,1,1,2018,1,Longford,Midlands,0,Deanscurragh Longford,Leinster,Other
253649,"Richmond St, Longford, Longford",NaN,Longford,52000.0,1,1,1,1,2018,7,Longford,Midlands,0,Richmond Street Longford,Leinster,Other
253653,"Ballymakeegan, Longford, Longford",NaN,Longford,220000.0,1,1,1,2,2021,1,Longford,Midlands,0,Ballymakeegan Longford,Leinster,Other
253654,"Aughadegnan, Longford, Longford",NaN,Longford,187500.0,1,1,1,2,2021,5,Longford,Midlands,0,Aughadegnan Longford,Leinster,Other
253655,"Lismore, Longford, Longford",NaN,Longford,50000.0,1,1,1,2,2021,7,Longford,Midlands,0,Lismore Longford,Leinster,Other

In [48]:
lon['Neighbourhood'].nunique()

120

In [49]:
lonn = pd.DataFrame(lon['Neighbourhood'].unique())

In [50]:
#lonn.to_csv('longford-neigh-unique.csv')

In [51]:
### typos
# Clonbolt Woods Longford - Clonbalt Woods Longford /done
# Clonbalt Wood Longford - ^^ /done
# Clonbalt Longford - ^^^  /done
# Ardnacasa Longford - Ardnacassagh /done
# Ardnacassa Lawns Longford - ^ /done
# Ard Na Cassa Longford - ^ /done
# Ardnacassa Manor Longford - ^^ /done
# Balinalee Road Longford /done
# The Demesne Longford - Demesne
# Demense Lane Longford - Demesne

In [52]:
rm_lon = ['Ferefad Longford', 'Lisduff Longford', 'Melview Longford', 'Lisbrack Longford', 'Lisnamuck Longford',
         'Ennybegs Longford', 'Lanesboro Longford', 'Tinnynarr Edgeworthstown Longford', 'Edgewardstown Longford',
         'Newtown Forbes Longford', 'Lismore Longford', 'Moydow Longford', 'Bornacoola Longford', 'Cloonbolt Longford',
         'Camlin Mews Longford', 'Ballymacormack Longford', 'Knockloughlin Longford', 'Lenamore Longford',
         'Coolarty Longford', 'Ballymakeegan Longford', 'Shroid Longford', 'Clonahard Longford', 'Stone Park Longford',
         'Kilashee Longford', 'Ballycloghan Longford', 'Ballyminion Longford', 'Dring Longford', 'Kenagh Longford',
         'Knockawalky Longford', 'Mostrim Longford', 'Farnagh Longford', 'White Linen Woods Longford', 'Cullyfad Longford',
         'Moyne Longford', 'Lanesboro Longford', 'Cahanagh Longford', 'Knockmartin Longford', 'Clondra Longford', 'Enybegs Longford']

In [53]:
irl.drop(irl[irl['Town'] == "Longford"].index, inplace=True)

In [54]:
lon.shape

(978, 16)

In [55]:
lon.drop(lon[lon['Neighbourhood'].isin(rm_lon)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [56]:
lon.loc[lon['Neighbourhood'].str.contains('Clonbalt'), 'Neighbourhood'] = 'Clonbalt Woods Longford'
lon.loc[lon['Neighbourhood'].str.contains('Clonbolt'), 'Neighbourhood'] = 'Clonbalt Woods Longford'
lon.loc[lon['Neighbourhood'].str.contains('Ardnacasa Longford'), 'Neighbourhood'] = 'Ardnacassagh Longford'
lon.loc[lon['Neighbourhood'].str.contains('Ardnacassa Lawns Longford'), 'Neighbourhood'] = 'Ardnacassagh Longford'
lon.loc[lon['Neighbourhood'].str.contains('Ard Na Cassa Longford'), 'Neighbourhood'] = 'Ardnacassagh Longford'
lon.loc[lon['Neighbourhood'].str.contains('Ardnacassa Manor Longford'), 'Neighbourhood'] = 'Ardnacassagh Longford'
lon.loc[lon['Neighbourhood'].str.contains('Balinalee Road Longford'), 'Neighbourhood'] = 'Ballinalee Road Longford'
lon.loc[lon['Neighbourhood'].str.contains('The Demesne Longford'), 'Neighbourhood'] = 'Demesne Longford'
lon.loc[lon['Neighbourhood'].str.contains('Demense Lane Longford'), 'Neighbourhood'] = 'Demesne Longford'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [57]:
lon.shape

(798, 16)

In [58]:
lon['Town'] = 'Longford Town'

C:\Users\user\AppData\Local\Temp/ipykernel_17744/3408773588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lon['Town'] = 'Longford Town'

In [59]:
irl = pd.concat([lon, irl], ignore_index = True)

In [60]:
irl

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
0,"42 Oakvale, Longford, Co Longford",NaN,Longford,31000.0,1,1,1,1,2013,12,Longford Town,Midlands,0,Oakvale Longford,Leinster,Estate
1,"Glack, Longford, Co Longford",NaN,Longford,115000.0,1,1,1,1,2014,10,Longford Town,Midlands,0,Glack Longford,Leinster,Other
2,"No 17 Battery Court, Longford, Co Longford",NaN,Longford,65000.0,1,1,1,2,2015,1,Longford Town,Midlands,0,Battery Court Longford,Leinster,Other
3,"Dublin Road, Longford, Co Longford",NaN,Longford,68000.0,1,1,1,1,2015,3,Longford Town,Midlands,0,Dublin Road Longford,Leinster,Other
4,"99 Teffia Park, Longford, Co Longford",NaN,Longford,60000.0,1,1,1,2,2015,8,Longford Town,Midlands,0,Teffia Park Longford,Leinster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255029,"5 Grange Park Rd, Waterford, Waterford",NaN,Waterford,515000.0,1,1,1,2,2021,2,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255030,"173 Hennessys Rd, Waterford, Waterford",NaN,Waterford,125000.0,1,1,1,2,2021,3,Waterford,South East (IE),0,Hennessys Road Waterford,Munster,Estate
255031,"15 Grange Park Rd, Waterford, Waterford",NaN,Waterford,390000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
255032,"40 Ballytruckle Rd, Waterford, Waterford",NaN,Waterford,115000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Ballytruckle Road Waterford,Munster,Estate
255033,"11 St Alphonsus Rd, Waterford, Waterford",NaN,Waterford,178000.0,1,1,1,2,2021,7,Waterford,South East (IE),0,St. Alphonsus Road Waterford,Munster,Estate

### Donegal

In [61]:
don

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
172891,"Portsalon, Donegal",NaN,Donegal,195000.0,1,1,1,2,2011,5,Donegal,Border,0,Portsalon Donegal,Ulster,Other
172895,"Linsfort House, Linsfort, Donegal",NaN,Donegal,530000.0,1,1,1,1,2012,7,Donegal,Border,0,Linsfort Donegal,Ulster,Other
172898,"33 Old Golf Course Road, Donegal",NaN,Donegal,171000.0,1,1,1,1,2012,11,Donegal,Border,0,Old Golf Course Road Donegal,Ulster,Estate
172900,"Lettertraine, Letterbarrow, Donegal",NaN,Donegal,34190.0,0,1,1,0,2013,4,Donegal,Border,0,Letterbarrow Donegal,Ulster,Other
172902,"2 Keshends, Newtowncunningham, Donegal",NaN,Donegal,120000.0,1,1,1,1,2013,10,Donegal,Border,0,Newtowncunningham Donegal,Ulster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175135,"Golard, Laghey, Donegal",NaN,Donegal,245000.0,1,1,1,2,2021,8,Donegal,Border,0,Laghey Donegal,Ulster,Other
175138,"Magherclogher, Derrybeg, Donegal",NaN,Donegal,312000.0,1,1,1,2,2021,9,Donegal,Border,0,Derrybeg Donegal,Ulster,Other
175139,"Tawnalary, Donegal Po, Donegal",NaN,Donegal,120000.0,1,1,1,2,2021,9,Donegal,Border,0,Donegal Po Donegal,Ulster,Other
175140,"Glenalla, Rathmullen, Donegal",NaN,Donegal,22000.0,1,1,1,2,2021,9,Donegal,Border,0,Rathmullen Donegal,Ulster,Other
231834,"Ballydevitt, Donegal, Co. Donegal",NaN,Donegal,85000.0,0,1,1,1,2014,12,Donegal,Border,0,Ballydevitt Donegal,Ulster,Other

In [62]:
don['Neighbourhood'].nunique()

47

In [63]:
donn = pd.DataFrame(don['Neighbourhood'].unique())

In [64]:
#donn.to_csv('donegal-neigh.csv')

In [65]:
### typos
# Donegal P O Donegal,

In [66]:
rm_don =['Newtowncunningham Donegal', 'Glenvar Donegal', 'Letterkenny Po Donegal', 'Rosnowlagh Donegal', 'Portsalon Donegal',
        'Letterbarrow Donegal', 'Derrybeg Donegal', 'Barnesmore Donegal', 'Quigleys Point Donegal', 'Castlefinn Donegal',
        'Kiltole Convoy Donegal', 'Gortahork Donegal', 'Bridge End Donegal', 'Drumcarbit Donegal', 'Malinmore Donegal',
        'Brinlack Donegal', 'Rinclevan Dunfanaghy Donegal', 'Rathmullen Donegal', 'Mount Charles Donegal', 'Portnoo Donegal',
        'Laghey Donegal', 'Fanad Donegal', 'Inver Po Donegal', 'Arranmore Island Donegal', 'Inch Island Donegal',
        'Manor Donegal', 'Malin Head Donegal', 'Drumkeen Donegal', 'Arranmore Donegal', 'Ballydevitt Donegal', 'Killygordan Donegal',
        'Drumbar Donegal', 'Tullycullion Donegal', 'Ballyboyle Donegal', 'Kilmacrenan Donegal', 'Letterkenny Po Donegal',
        'Drumboe Donegal', 'Lecamey Donegal']

In [67]:
irl.drop(irl[irl['Town'] == "Donegal"].index, inplace=True)

In [68]:
don.shape

(282, 16)

In [69]:
don.drop(don[don['Neighbourhood'].isin(rm_don)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [70]:
don.shape

(29, 16)

In [71]:
don['Town'] = 'Donegal Town'

C:\Users\user\AppData\Local\Temp/ipykernel_17744/3581363427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  don['Town'] = 'Donegal Town'

In [72]:
irl = pd.concat([don, irl], ignore_index = True)

In [73]:
irl

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
0,"Linsfort House, Linsfort, Donegal",NaN,Donegal,530000.0,1,1,1,1,2012,7,Donegal Town,Border,0,Linsfort Donegal,Ulster,Other
1,"33 Old Golf Course Road, Donegal",NaN,Donegal,171000.0,1,1,1,1,2012,11,Donegal Town,Border,0,Old Golf Course Road Donegal,Ulster,Estate
2,"Donnan, Donegal Po, Donegal",NaN,Donegal,130000.0,1,1,1,2,2013,11,Donegal Town,Border,0,Donegal Po Donegal,Ulster,Other
3,"32 Orchard Park, Donegal",NaN,Donegal,95000.0,1,1,1,2,2013,12,Donegal Town,Border,0,Orchard Park Donegal,Ulster,Estate
4,"Ph 2 Fortwell Apts, Main St, Donegal",NaN,Donegal,25000.0,1,1,1,0,2014,3,Donegal Town,Border,1,Main Street Donegal,Ulster,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254776,"5 Grange Park Rd, Waterford, Waterford",NaN,Waterford,515000.0,1,1,1,2,2021,2,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
254777,"173 Hennessys Rd, Waterford, Waterford",NaN,Waterford,125000.0,1,1,1,2,2021,3,Waterford,South East (IE),0,Hennessys Road Waterford,Munster,Estate
254778,"15 Grange Park Rd, Waterford, Waterford",NaN,Waterford,390000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Grange Park Road Waterford,Munster,Estate
254779,"40 Ballytruckle Rd, Waterford, Waterford",NaN,Waterford,115000.0,1,1,1,2,2021,5,Waterford,South East (IE),0,Ballytruckle Road Waterford,Munster,Estate
254780,"11 St Alphonsus Rd, Waterford, Waterford",NaN,Waterford,178000.0,1,1,1,2,2021,7,Waterford,South East (IE),0,St. Alphonsus Road Waterford,Munster,Estate

In [74]:
irl.loc[irl['Neighbourhood'].str.contains("Donegal P O Donegal"), 'Neighbourhood'] = 'Donegal PO Donegal'

### Monaghan

In [75]:
mon

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
179638,"Apt 1 88 Glaslough St, Monaghan, Co Monaghan",NaN,Monaghan,27334.0,1,1,1,2,2014,5,Monaghan,Border,1,Mill Street Monaghan,Ulster,Other
179639,"58 Beechgrove Lawns, Monaghan, Co Monaghan",NaN,Monaghan,60000.0,1,1,1,1,2014,5,Monaghan,Border,0,Beechgrove Lawns Monaghan,Ulster,Estate
179644,"145 Mullaghmatt, Monaghan, Co Monaghan",NaN,Monaghan,43000.0,1,1,1,1,2014,10,Monaghan,Border,0,Mullaghmatt Monaghan,Ulster,Estate
179648,"4 Westenra Terrace, Monaghan, Co Monaghan",NaN,Monaghan,17500.0,0,1,1,2,2014,12,Monaghan,Border,0,Westenra Terrace Monaghan,Ulster,Estate
179659,"11 Killyconnigan, Monaghan, Co Monaghan",NaN,Monaghan,117000.0,1,1,1,1,2015,3,Monaghan,Border,0,Killyconnigan Monaghan,Ulster,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236666,"3 Coolshannagh, Monaghan, County Monaghan",NaN,Monaghan,165000.0,1,1,1,1,2020,9,Monaghan,Border,0,Coolshannagh Monaghan,Ulster,Estate
253708,"Doora, Laragh, Monaghan",NaN,Monaghan,180000.0,1,1,1,1,2016,2,Monaghan,Border,0,Laragh Monaghan,Ulster,Other
253710,"39 Thorndale, Bree, Monaghan",NaN,Monaghan,120000.0,0,1,1,1,2016,9,Monaghan,Border,0,Bree Monaghan,Ulster,Estate
253714,"Corkashybane, Laragh, Monaghan",NaN,Monaghan,280000.0,1,1,1,1,2018,2,Monaghan,Border,0,Laragh Monaghan,Ulster,Other
253717,"Knockatallon, Monaghan, Monaghan",NaN,Monaghan,30000.0,1,1,1,1,2019,4,Monaghan,Border,0,Knockatallon Monaghan,Ulster,Other

In [76]:
mon['Neighbourhood'].nunique()

98

In [77]:
monn = pd.DataFrame(mon['Neighbourhood'].unique())
#monn.to_csv('mon-neigh.csv')

In [78]:
### Typos
# Latlurcan Glen Monaghan -  latlorcan glen monaghan
# Latlorcan Monaghan
# Mullach Glas Crescent Monaghan - drop crescent
# Mullagh Glas Crescent Monaghan - mullach
# Latlurcan Monaghan - lorcan
# Mullach Glas Cresent Monaghan
# Ropewalk Monaghan - Rope Walk
# Monaghan Town Monaghan
# Latlorcan Dublin Road Monaghan

In [79]:
rm_mon = ['Mullaghmatt Monaghan', 'Corlat Monaghan', 'Tully Monaghan', 'Hillside Monaghan', 'Beaghkearns Monaghan', 
         'Tullycroman Monaghan', 'Tullyherim Monaghan', 'Derrynagrew Monaghan', 'Stranooden Monaghan', 'Kilnacloy Monaghan',
         'Manorwood Monaghan', 'Mullaghdun Monaghan', 'Milltown Monaghan', 'Tyholland Monaghan', 'Gallinagh Monaghan',
         'Killygoan Monaghan', 'Drumbear Monaghan', 'Tyleadon Monaghan', 'Dernagrew Monaghan', 'Cormeen Monaghan',
         'Millbrook Monaghan', 'Dunraymond Monaghan', 'Ballyalbany Monaghan', 'Knockatallon Monaghan', 'Castleblaney Monaghan',
         'Shantonagh Monaghan', 'Corcaghan Monaghan', 'Riverside Monaghan', 'Smithboro Monaghan', 'Silverstream Monaghan',
         'Tirnaneill Monaghan', 'Lisnalong Monaghan', 'Coolmain Monaghan', 'Three Mile House Monaghan', 'Carrickroe Monaghan',
         'Aghabog Monaghan', 'Iniskeen Monaghan', 'Aghananimy Monaghan', 'The Meadows Smithboro Monaghan', 'Aughnaseda Monaghan',
         'Laragh Monaghan']

In [80]:
irl.drop(irl[irl['Town'] == "Monaghan"].index, inplace=True)

In [81]:
mon.shape

(552, 16)

In [82]:
mon.drop(mon[mon['Neighbourhood'].isin(rm_mon)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [83]:
mon.shape

(361, 16)

In [84]:
mon['Town'] = 'Monaghan Town'
irl = pd.concat([mon, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/2368103917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['Town'] = 'Monaghan Town'

In [85]:
irl.loc[irl['Neighbourhood'].str.contains("Latlurcan"), 'Neighbourhood'] = 'Latlorcan Monaghan'

In [86]:
irl.loc[irl['Neighbourhood'].str.contains("Mullagh Glas"), 'Neighbourhood'] = 'Mullach Glas'

In [87]:
irl.loc[irl['Neighbourhood'].str.contains("Latlorcan"), 'Neighbourhood'] = 'Latlorcan'

In [88]:
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Beech'), 'Neighbourhood'] = 'Beechgrove'

In [89]:
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan")]

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
206,"68 Tully, Monaghan Town, Monaghan",NaN,Monaghan,58200.0,1,1,1,1,2016,9,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
274,"7 Russell Court, Monaghan Town, Monaghan",NaN,Monaghan,71000.0,1,1,1,1,2018,11,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
280,"23 High St, Monaghan Town, Monaghan",NaN,Monaghan,146000.0,1,1,1,2,2018,12,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
290,"99 Mullaghmatt, Monaghan Town, Monaghan",NaN,Monaghan,53269.0,1,1,1,1,2019,5,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
309,"31 Canal View, Monaghan Town, Monaghan",NaN,Monaghan,212000.0,1,1,1,1,2019,8,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
324,"8 Latlurcan Glen, Monaghan Town, Monaghan",NaN,Monaghan,140000.0,1,1,1,1,2020,4,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate
337,"4 Cortolvin View, Monaghan Town, Monaghan",NaN,Monaghan,131592.0,1,1,1,2,2020,12,Monaghan Town,Border,0,Monaghan Town Monaghan,Ulster,Estate

In [90]:
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Tully'), 'Neighbourhood'] = 'Tully Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Russell'), 'Neighbourhood'] = 'Russell Court Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('High St'), 'Neighbourhood'] = 'High Street Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Mullaghmatt'), 'Neighbourhood'] = 'Mullaghmatt Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Canal'), 'Neighbourhood'] = 'Canal View Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Latlurcan'), 'Neighbourhood'] = 'Latlurcan Monaghan'
irl.loc[irl['Neighbourhood'].str.contains("Monaghan Town Monaghan") & irl['Address'].str.contains('Cortolvin View'), 'Neighbourhood'] = 'Cortolvin View Monaghan'

In [91]:
irl.loc[irl['Neighbourhood'] == "Ropewalk Monaghan", 'Neighbourhood'] = 'Rope Walk Monaghan'

### Cavan

In [92]:
#cav['Neighbourhood'].nunique()
cavn = pd.DataFrame(cav['Neighbourhood'].unique())

In [93]:
cav['Neighbourhood'].nunique()

130

In [94]:
cavn.to_csv('cav-neigh.csv')

In [95]:
### Typos
# Swellan Cavan - upper and lower to be all called this /done
# College Stree Cavan - street /done
# Swellen Cavan /done
# Cock Hill Cavan - Cockhill /done
# The Gallops Latt Cavan - The Gallops /done
# Drumgolawoods Cavan - spaces /done
# Loretto Wood Cavan

In [96]:
rm_cav = ['Swellan Lower Cavan', 'Baileborough Cavan', 'Moynehall Cavan', 'Billis Cavan', 'Drung Cavan', 'Drumnavannagh Cavan',
         'Stragelliffe Cavan', 'Crubany Cavan', 'Carrickane Cavan', 'Drumconnick Cavan', 'Cloverhill Cavan', 'Virginia Road Ballyjamesduff Cavan',
         'Poles Cavan', 'Fairtown Cavan', 'Drumnavanagh Cavan', 'Farnham Cavan', 'Corlurgan Cavan', 'Loch Gowna Cavan', 'Virgina Cavan',
         'Cornafean Cavan', 'Corlismore Cavan', 'Killinkere Cavan', 'Drumgola Cavan', 'Coothill Cavan', 'Oldtown Manor Cavan',
         'Farnham Estate Cavan', 'Arva Cavan', 'Fairgreen Cavan', 'Mount Nugent Cavan', 'Drumbo Cavan', 'Bailiborough Cavan',
         'Cavan Po Cavan', 'Carrickaboy Cavan', 'Crosserlough Cavan', 'Crosskeys Cavan', 'Blenacup Cavan', 'Killykeen Cavan',
         'Gowna Cavan', 'Butlers Bridge Cavan', 'Bailieboro Cavan', 'Tierquin Cavan', 'Ballyheelan Cavan', 'Loughduff Cavan', 
         'Bailiebourough Cavan', 'Ballyconnel Cavan', 'Drumc Avenue Cavan', 'Louth Gowna Cavan', 'Glangelvin Cavan', 'Drumcor Cavan',
         'Burlersbridge Cavan', 'Annaglough Cavan', 'Farnham Close Cavan', 'Oldtown Cavan', 'Shankill Cavan', 'Kells Road Mullagh Cavan']

In [97]:
cav.shape

(1053, 16)

In [98]:
irl.drop(irl[irl['Town'] == "Cavan"].index, inplace=True)

In [99]:
cav.drop(cav[cav['Neighbourhood'].isin(rm_cav)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [100]:
cav.shape

(717, 16)

In [101]:
cav.loc[cav['Neighbourhood'].str.contains("Swellan"), 'Neighbourhood'] = 'Swellan Cavan'
cav.loc[cav['Neighbourhood'].str.contains("Swellen"), 'Neighbourhood'] = 'Swellan Cavan'
cav.loc[cav['Neighbourhood'].str.contains("Cockhill"), 'Neighbourhood'] = 'Cock Hill Cavan'
cav.loc[cav['Neighbourhood'].str.contains("College Stree Cavan"), 'Neighbourhood'] = 'College Street Cavan'
cav.loc[cav['Neighbourhood'].str.contains("The Gallops Latt Cavan"), 'Neighbourhood'] = 'The Gallops Cavan'
cav.loc[cav['Neighbourhood'].str.contains("Drumgolawoods Cavan"), 'Neighbourhood'] = 'Drumgola Woods Cavan'
cav.loc[cav['Neighbourhood'].str.contains("Loretto Wood Cavan"), 'Neighbourhood'] = 'Loreto Wood Cavan'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [102]:
cav['Town'] = 'Cavan Town'
irl = pd.concat([cav, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/139353217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cav['Town'] = 'Cavan Town'

### Waterford

In [103]:
wat.shape

(3764, 16)

In [104]:
wat['Neighbourhood'].nunique()

336

In [105]:
watt = pd.DataFrame(wat['Neighbourhood'].unique())
#watt.to_csv('wat-neigh.csv')

In [106]:
### Typos
# Kingschannel Waterford /done
# Morrissons Road Waterford - Morrisson's Road Waterford /done
# Philip Street Waterford /done
# Grace Dieu Waterford - multiple versions of this, Gracdieu Waterford   /done
# Summerhill Tce Waterford - Tce is Terrace /done
# Morrison's Road Waterford - extra s /done
# Morrisons Road Waterford /done
# Roanmore Pk Waterford - Park /done
# Gracedieu Heights Waterford - drop heights /done
# Kill St Lawrence Waterford - St. /done
# change all Ardkeen /done
# Oconnell Street Waterford, O' Connell Street Waterford /done
# Ballygunnar Waterford /done
# Farranshoneen Waterford - Farronshoneen Waterford /done
# Templers Hall Waterford - Templar /done
# O Brien Street Waterford /done
# Poolberry Waterford - Poleberry Waterford /done
# B, C, D Adelphi Quay Waterford  /done
# A O'Connell Street Waterford /done

In [107]:
rm_wat = ['Cherrymount Waterford', 'Grantstown Waterford', 'Knockboy Waterford', 'Maypark Village Waterford', 'Ballinamona Waterford',
         'Kilcohan Waterford', 'Halfway House Waterford', 'Cappagh Waterford', 'Newrath Waterford', 'Ballinaneeshagh Waterford',
         'Faithlegg Waterford', 'Ballinaneashagh Waterford', 'Carrick On Suir Waterford', 'Butlerstown Waterford', 'Ballyduff Waterford',
         'Bonmahon Waterford', 'Leamybrien Waterford', 'Ballyduff Upper Waterford', 'Woodstown Waterford', 'Killure Waterford',
         'Ring Waterford', 'Templars Hall Kilbarry Waterford', 'Kilbarry Waterford', 'Abbeyside Waterford', 'Dungarven Waterford',
         'Faithlegge Waterford', 'Pebble Beach Waterford', 'Ballymacarbery Waterford', 'Graigueshoneen Kilmacthomas Waterford',
         'Via Youghal Waterford', 'Airmount Waterford', 'Farmleigh Dunmore Road Waterford', 'Clonmel Waterford', 'Lismore Pk Waterford',
          'Carrigeen Pk Waterford', 'Obrien Street Waterford', 'St. Johns Pk Waterford', 'Congress Pl Waterford', 'The Burgery Dungarvan Waterford',
         'Henry St Terrace Waterford', 'Abbeyside Dungarvan Waterford', 'Morley Tce Waterford', 'Newtown Waterford', 'Carrickpherish Waterford',
         'Carrigeen Kill Waterford', 'Lower Dunmore E Street Waterford']

In [108]:
irl.drop(irl[irl['Town'] == "Waterford"].index, inplace=True)

In [109]:
wat.drop(wat[wat['Neighbourhood'].isin(rm_wat)].index, inplace=True)

In [110]:
wat.shape

(3349, 16)

In [111]:
wat.loc[wat['Neighbourhood'].str.contains("Gracedieu"), 'Neighbourhood'] = 'Gracedieu'
wat.loc[wat['Neighbourhood'].str.contains("Grace Dieu"), 'Neighbourhood'] = 'Gracedieu'
wat.loc[wat['Neighbourhood'].str.contains("Morrissons Road Waterford"), 'Neighbourhood'] = "Morrisson's Road Waterford"
wat.loc[wat['Neighbourhood'].str.contains("Morrisons Road Waterford"), 'Neighbourhood'] = "Morrisson's Road Waterford"
wat.loc[wat['Neighbourhood'].str.contains("Morrison's Road Waterford"), 'Neighbourhood'] = "Morrisson's Road Waterford"
wat.loc[wat['Neighbourhood'].str.contains("Adelphi Quay"), 'Neighbourhood'] = "Adelphi Quay Waterford"
wat.loc[wat['Neighbourhood'].str.contains("Kingschannel Waterford"), 'Neighbourhood'] = 'Kings Channel Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Philip Street Waterford"), 'Neighbourhood'] = 'Phillip Street Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Summerhill Tce Waterford"), 'Neighbourhood'] = 'Summerhill Terrace Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Roanmore Pk Waterford"), 'Neighbourhood'] = 'Roanmore Park Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Kill St Lawrence Waterford"), 'Neighbourhood'] = 'Kill St. Lawrence Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Ardkeen"), 'Neighbourhood'] = 'Ardkeen Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Connell Street"), 'Neighbourhood'] = "O'Connell Street Waterford"
wat.loc[wat['Neighbourhood'].str.contains("Ballygunnar Waterford"), 'Neighbourhood'] = 'Ballygunner Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Farranshoneen Waterford"), 'Neighbourhood'] = 'Farronshoneen Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Templers Hall Waterford"), 'Neighbourhood'] = 'Templers Hall Waterford'
wat.loc[wat['Neighbourhood'].str.contains("Brien Street"), 'Neighbourhood'] = "O'Brien Street"
wat.loc[wat['Neighbourhood'].str.contains("Poolberry Waterford"), 'Neighbourhood'] = 'Poleberry Waterford'

In [112]:
wat['Town'] = 'Waterford City'
irl = pd.concat([wat, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/2965434689.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wat['Town'] = 'Waterford City'

### Limerick

In [113]:
lim.shape

(5329, 16)

In [114]:
lim['Neighbourhood'].nunique()

280

In [115]:
limm = pd.DataFrame(lim['Neighbourhood'].unique())
#limm.to_csv('lim-neigh.csv')

In [116]:
### Typos
# Fr. Russell Road Limerick - has 4 diff versions /done
# Mount Kennett Limerick - Kenneth, also kenneth place make all the same /done
# O Curry Street Limerick - O'
# Ocallaghan Strand Limerick
# Ballykeefe Limerick - two f's /done
# Oconnell Avenue Limerick, O Connell Avenue Limerick /done
# Castleroy Limerick - Castletroy, also anything containing castletroy /done
# Glencairin Limerick - Glencairn /done
# Bishops Quay - multiple /done

In [117]:
rm_lim = ['Prospect Limerick', 'Church Hill Meadows Raheen Limerick', 'Monaleen Limerick', 'Corbally Limerick', 'Farranshone Limerick',
         'Clarina Village Limerick', 'Ballygrennan Limerick', 'Kilcornan Limerick', 'Ballysimon Limerick', 'Scr Limerick', 'Anglesborough Limerick',
         'Kilfinane Limerick', 'Castlemahon Limerick', 'Killalee Limerick', 'Loughill Limerick', 'Caherline Limerick', 'Newcastle Limerick',
         'Grove Island Limerick', 'Roxboro Limerick', 'Ballinacurra Weston Rosbrien Limerick', 'Drombanna Limerick',
          'Templeglantine W Street Limerick', 'Coonagh Limerick', 'Reens Ardagh Limerick', 'Cornmarket Limerick', 'Ballycummin Village Limerick',
         'Old Pallas Limerick', 'Mount Collins Limerick', 'Shannonvale Old Cratloe Road Limerick', 'Pallasgrean Limerick', 'Ashdown Village Limerick',
         'S C Road Limerick', 'New Road Limerick', 'Monagea Limerick', 'Carn Na Ri Old Singland Road Limerick', 'Brittas Limerick',
         'Ballyclough Limerick', 'Carrigkerry Limerick', 'Toomaline Doon Limerick', 'Spitland Limerick', 'Ocallaghans Strand Limerick',
         'Punches Cross Limerick', 'Thomond Village Limerick', 'Charleville Limerick', 'Glenmore Limerick']

In [118]:
irl.drop(irl[irl['Town'] == "Limerick"].index, inplace=True)

In [119]:
lim.shape

(5329, 16)

In [120]:
lim.drop(lim[lim['Neighbourhood'].isin(rm_lim)].index, inplace=True)

In [121]:
lim.shape

(4772, 16)

In [122]:
lim.loc[lim['Neighbourhood'].str.contains("O Curry Street Limerick"), 'Neighbourhood'] = "O'Curry Street Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Ocallaghan Strand Limerick"), 'Neighbourhood'] = "O'Callaghan Strand Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Glencairin"), 'Neighbourhood'] = 'Glencairn Limerick'
lim.loc[lim['Neighbourhood'].str.contains("Glencairn"), 'Neighbourhood'] = 'Glencairn Limerick'
lim.loc[lim['Neighbourhood'].str.contains("Ballykeefe"), 'Neighbourhood'] = 'Ballykeeffe Limerick'
lim.loc[lim['Neighbourhood'].str.contains("connell Avenue"), 'Neighbourhood'] = "O'Connell Avenue Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Connell Avenue"), 'Neighbourhood'] = "O'Connell Avenue Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Russell"), 'Neighbourhood'] = 'Father Russell Road Limerick'
lim.loc[lim['Neighbourhood'].str.contains("Kennett"), 'Neighbourhood'] = "Mount Kenneth Place Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Kenneth"), 'Neighbourhood'] = "Mount Kenneth Place Limerick"
lim.loc[lim['Neighbourhood'].str.contains("Castleroy"), 'Neighbourhood'] = 'Castletroy Limerick'
lim.loc[lim['Neighbourhood'].str.contains("Bishops Quay"), 'Neighbourhood'] = 'Bishops Quay Limerick'

In [123]:
lim['Town'] = 'Limerick City'
irl = pd.concat([lim, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/2173106929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lim['Town'] = 'Limerick City'

### Sligo

In [124]:
sli = irl.loc[irl['Town'] == 'Sligo']

In [125]:
sli

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
172032,"17 Quay St, Sligo, Co Sligo",NaN,Sligo,100000.0,1,1,1,1,2015,3,Sligo,Border,0,Quay Street Sligo,Connacht,Estate
172047,"105 Rathbraughan Park, Sligo, Co Sligo",NaN,Sligo,30000.0,1,1,1,1,2016,3,Sligo,Border,0,Rathbraughan Park Sligo,Connacht,Estate
172049,"12 Stephen Street, Sligo, Co Sligo",NaN,Sligo,72500.0,1,1,1,1,2016,4,Sligo,Border,0,Stephen Street Sligo,Connacht,Estate
172068,"17 The Mall, Sligo, Co Sligo",NaN,Sligo,67500.0,1,1,1,1,2016,6,Sligo,Border,0,The Mall Sligo,Connacht,Estate
172071,"15 Devins Drive, Sligo, Co Sligo",NaN,Sligo,55000.0,1,1,1,1,2016,7,Sligo,Border,0,Devins Drive Sligo,Connacht,Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251599,"Brackloonagh, Charlestown, Sligo",NaN,Sligo,45000.0,1,1,1,2,2021,7,Sligo,Border,0,Charlestown Sligo,Connacht,Other
253237,"8 White Crest, Pier Rd Enniscrone, Sligo",NaN,Sligo,72000.0,1,1,1,0,2016,4,Sligo,Border,0,Pier Road Enniscrone Sligo,Connacht,Estate
253238,"10 White Crest Village, Pier Rd Enniscrone, Sligo",NaN,Sligo,130000.0,1,1,1,2,2019,12,Sligo,Border,0,Pier Road Enniscrone Sligo,Connacht,Estate
253239,"Cascia, Strandhill Rd Sligo, Sligo",NaN,Sligo,235000.0,1,1,1,1,2020,2,Sligo,Border,0,Strandhill Road Sligo Sligo,Connacht,Other
253240,"Lisroe, Strandhill Rd Sligo, Sligo",NaN,Sligo,355000.0,1,1,1,2,2021,3,Sligo,Border,0,Strandhill Road Sligo Sligo,Connacht,Other

In [126]:
#irl.loc[irl['Town'] == 'Sligo Town']

In [127]:
sli['Neighbourhood'].nunique()

200

In [128]:
sligo = pd.DataFrame(sli['Neighbourhood'].unique())
#sligo.to_csv('sligo-neigh.csv')

In [129]:
### Typos
# City Gate Sligo - Citygate Sligo
# Jfk Parade Sligo, J F K Parade Sligo, John F Kennedy Parade Sligo
# Brooklawns First Sea Road Sligo - Brooklawns
# Maugheraboy Sligo

In [130]:
rm_sligo = ['Charlestown Sligo', 'Bunninadden Sligo', 'Drumcliffe Sligo', 'Drumnacool Sligo', 'Inniscrone Sligo', 'Easkey Sligo',
           'Ballymoate Sligo', 'Ballydoogan Sligo', 'The Meadows Grange Sligo', 'Dromard Sligo', 'Kilmacowen Sligo',
           'Ballisadare Sligo', 'Castlecove Enniscrone Sligo', 'Bunnanaddan Sligo', 'Curry Sligo', 'Ballinacarrow Sligo',
           'The Bridge Strandhill Sligo', 'Templeboy Sligo', 'Via Boyle Sligo', 'Carroroe Sligo', 'Knappaghmore Sligo',
           'Kiltykere Grange Sligo', 'Ransboro Sligo', 'Cliffony Sligo', 'Moneygold Sligo', 'Kilmactranny Sligo', 
           'Cummeen Sligo', 'Drumfin Sligo', 'Aughamore Near Sligo', 'Cooloney Sligo', 'Abbey St Lower Sligo', 
           'Rathbraughan Sligo', 'Lisnalurg Sligo', 'Culfadda Sligo', 'Castledargan Sligo', 'Colgagh Sligo', 'Dunally Sligo',
           'Inishcrone Sligo', 'Barroe Sligo', 'Clogherevagh Sligo', 'Carrowmore Sligo', 'Knockbeg Sligo', 'Colooney Sligo',
           'Moneygold Grange Sligo', "St. Angel's Student Residences Sligo", 'Castlegal Sligo', 'Rathcormac Sligo',
           'Boyle Sligo', 'Glencar Sligo', 'Pier Road Enniscrone Sligo', 'Strandhill Road Sligo Sligo', 'Ballinful Sligo']

In [131]:
irl.drop(irl[irl['Town'] == "Sligo"].index, inplace=True)

In [132]:
sli.drop(sli[sli['Neighbourhood'].isin(rm_sligo)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [133]:
sli.shape

(1350, 16)

In [134]:
sli.loc[sli['Neighbourhood'].str.contains("Kennedy"), 'Neighbourhood'] = 'John F Kennedy Parade Sligo'
sli.loc[sli['Neighbourhood'].str.contains("Jfk"), 'Neighbourhood'] = 'John F Kennedy Parade Sligo'
sli.loc[sli['Neighbourhood'].str.contains("J F K"), 'Neighbourhood'] = 'John F Kennedy Parade Sligo'
sli.loc[sli['Neighbourhood'].str.contains("Maugheraboy"), 'Neighbourhood'] = 'Maugheraboy Sligo'
sli.loc[sli['Neighbourhood'].str.contains("Brooklawns"), 'Neighbourhood'] = 'Brooklawns Sligo'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [135]:
sli['Town'] = 'Sligo Town'
irl = pd.concat([sli, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/2381079714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sli['Town'] = 'Sligo Town'

## Carlow

In [136]:
car = irl.loc[irl['Town'] == 'Carlow']

In [137]:
car

,Address,Postal Code,County,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Year,Month,Town,Region,Apartment,Neighbourhood,Province,Estate
202255,"2 Johnsmill, Carlow, Co Carlow",NaN,Carlow,35000.0,1,1,1,1,2013,12,Carlow,South East (IE),0,Johnsmill Carlow,Leinster,Estate
202256,"7 Johnsmill, Carlow, Co Carlow",NaN,Carlow,35000.0,1,1,1,1,2013,12,Carlow,South East (IE),0,Johnsmill Carlow,Leinster,Estate
202261,"No 7 Huntingdon Court, Carlow, Co Carlow",NaN,Carlow,98500.0,1,1,1,1,2014,7,Carlow,South East (IE),0,Huntingdon Court Carlow,Leinster,Other
202262,"22 Highfield, Carlow, Co Carlow",NaN,Carlow,190000.0,1,1,1,1,2014,10,Carlow,South East (IE),0,Highfield Carlow,Leinster,Estate
202273,"Kyleballyhue, Carlow, Co Carlow",NaN,Carlow,300000.0,1,1,1,2,2015,6,Carlow,South East (IE),0,Kyleballyhue Carlow,Leinster,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252076,"Cloydah, Carlow, Carlow",NaN,Carlow,320000.0,1,1,1,2,2021,3,Carlow,South East (IE),0,Cloydah Carlow,Leinster,Other
252077,"60 Woodglade, Fenagh, Carlow",NaN,Carlow,170000.0,1,1,1,2,2021,3,Carlow,South East (IE),0,Fenagh Carlow,Leinster,Estate
252078,"Staplestown, Carlow",NaN,Carlow,60000.0,1,1,1,2,2021,6,Carlow,South East (IE),0,Staplestown Carlow,Leinster,Other
252079,"51 Woodglade, Fenagh, Carlow",NaN,Carlow,194000.0,1,1,1,2,2021,6,Carlow,South East (IE),0,Fenagh Carlow,Leinster,Estate
252080,"Church Lane, Staplestown, Carlow",NaN,Carlow,476000.0,1,1,1,2,2021,8,Carlow,South East (IE),0,Staplestown Carlow,Leinster,Other

In [138]:
car['Neighbourhood'].nunique()

138

In [139]:
carl = pd.DataFrame(car['Neighbourhood'].unique())
#carl.to_csv('carlow-neigh.csv')

In [140]:
### Typos
# Hay Market Carlow -> one word /done
# Carlow Town Carlow
# Jkl Avenue Carlow -> Kennedy Avenue /done
# Castle Oaks Carlow, Castleoaks -> make common /done
# Browneshill Carlow -> all containing this
# Hackettstown Road Carlow -> one less t

In [141]:
rm_carlow = ['Kyleballyhue Carlow', 'Kellistown Carlow', 'Graiguecullen Carlow', 'Mortarstown Carlow', 'Springhill Carlow',
            'Bunclody Carlow', 'Staplestown Carlow', 'Kilbride Carlow', 'Fenagh Carlow', 'Killeshin Carlow', 'Ballyhide Carlow',
            'Ballycrogue Carlow', 'Bagnelstown Carlow', 'Garryhill Carlow', 'Cloydah Carlow', 'Bagnalstown Carlow', 
            'Craigcullen Carlow', 'Killerig Carlow', 'Graigcullen Carlow', 'Chapelstown Carlow', 'Newtownallen Carlow',
            'Tinnahinch Carlow', 'Straboe Carlow', 'Milford Carlow', 'Raheendoran Carlow', 'Rathoe Carlow', 'Brownshill Carlow',
            'Bennekerry Carlow', 'Knocknagee Carlow', 'Ballinabrannagh Carlow', 'Quinagh Carlow', 'Brownshill Road Carlow',
            'Ballinabranagh Carlow', 'Saint Mullins Carlow']

In [142]:
irl.drop(irl[irl['Town'] == "Carlow"].index, inplace=True)

In [143]:
car.drop(car[car['Neighbourhood'].isin(rm_carlow)].index, inplace=True)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [144]:
car.loc[car['Neighbourhood'].str.contains("Jkl"), 'Neighbourhood'] = 'Kennedy Avenue Carlow'
car.loc[car['Neighbourhood'].str.contains("Hay Market"), 'Neighbourhood'] = 'Haymarket Carlow'
car.loc[car['Neighbourhood'].str.contains("Castle Oaks"), 'Neighbourhood'] = 'Castleoaks Carlow'
car.loc[car['Neighbourhood'].str.contains("Hackettstown"), 'Neighbourhood'] = 'Hacketstown Road Carlow'

C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [145]:
car['Town'] = 'Carlow Town'
irl = pd.concat([car, irl], ignore_index = True)

C:\Users\user\AppData\Local\Temp/ipykernel_17744/1046386334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['Town'] = 'Carlow Town'

## Kilkenny

In [147]:
kilk = irl.loc[irl['Town'] == 'Kilkenny']
kilk.shape

(1825, 16)

In [148]:
kilk['Neighbourhood'].nunique()

204

In [149]:
kilkk = pd.DataFrame(kilk['Neighbourhood'].unique())
kilkk.to_csv('kilkenny-neigh.csv')

In [146]:
#irl.to_csv('tidied-towns.csv')